### ISSUE TITLE
Importing the C API fails on Windows

### ISSUE THREAD

**Issue by robertodr** [mpi4py/mpi4py#19]
I am trying to build a C++ Python extension (with pybind11) that uses MPI and mpi4py on Windows. I am working in a conda environment and I installed mpi4py as follows:

```shell
conda install mpi4py -c conda-forge --yes
```

The following:

```c++
// import the mpi4py API
if (import_mpi4py() < 0) {
  throw std::runtime_error("Could not load mpi4py API.");
}
```
throws the exception with traceback:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\IEUser\VeloxChemMP\build_dbg_14.27\lib\python3.8\site-packages\veloxchem\__init__.py", line 2, in <module>
    from .veloxchemlib import AtomBasis
ImportError: Could not load mpi4py API.
```

Running `mpiexec -n 4 python -c “from mpi4py import MPI; comm = MPI.COMM_WORLD; print(comm.Get_rank())”` works as expected. I am not sure whether this is a bug or some silly mistake I am making.

This issue was migrated from moved from BitBucket [#177](https://bitbucket.org/mpi4py/mpi4py/issues/177)

**Comment by dalcinl** [comment]
Oh, sorry, I should have figured it out... The problem is that your wrapper is swallowing the actual Python exception and traceback, so this is not really useful. 

Can you try to build and run the code in mpi4py's `demo/wrap-c` directory? If that one fails, we should get the nice traceback we are looking for.

**Comment by robertodr** [comment]
OK, here it is:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ValueError: mpi4py.MPI.Message size changed, may indicate binary incompatibility. Expected 40 from C header, got 32 from PyObject
```

**Comment by dalcinl** [comment]
Ups, now I see the problem... 

Fix your code this way:

```
#define PyMPI_HAVE_MPI_Message 1
#include <mpi4py/mpi4py.h>
...
```

Look at `mpi4py.h` and you will notice what's going on. I should attempt to do this in a smarter way. Perhaps check whether `MPI_MESSAGE_NULL ` is defined, and if it is, then skip that bogus definition for `MPI_Message`.

**Comment by robertodr** [comment]
A-ha! Yes, I see what's happening! For the moment I'll fence that `define` as:
```c++
#ifdef _WIN32
#define PyMPI_HAVE_MPI_Message 1
#endif
```
By the way, is it possible to get an error message from `import_mpi4py` rather than just an error code?

**Comment by dalcinl** [comment]
Perhaps you want to be even more specific, and fence with something like `#ifdef MSMPI_VER`.

About more specific error messages... It is not so trivial, `import_mpi4py()` calls Cython-generated code, and I have little control over it. The Cython-generated code performs Python imports and attribute lookups. In case of failure, a Python exception is set. You can use `PyErr_*` Python C APIs, for example:

```C
if (import_mpi4py() < 0) {
  PyErr_Print();
  throw std::runtime_error("Could not load mpi4py API.");
}
```

**Comment by dalcinl** [comment]
What about the following way? [[link]](https://pybind11.readthedocs.io/en/stable/advanced/exceptions.html#handling-errors-from-the-python-c-api)

```c++
if (import_mpi4py() < 0) { throw py::error_already_set(); }
```

**Comment by robertodr** [comment]
Thanks the help! Do you wish this issue to be kept open until you figure out a more permanent fix?

**Comment by dalcinl** [comment]
@robertodr Could you please try the `bugfix/msmpi` branch I just pushed (commit 169f0fa)?

**Comment by robertodr** [comment]
> @robertodr Could you please try the `bugfix/msmpi` branch I just pushed (commit [169f0fa](https://github.com/mpi4py/mpi4py/commit/169f0fa5e5f74ae5b40471cf91dafc47de46db57))?

Hopefully in the weekend!

**Comment by robertodr** [comment]
OK, I finally got around to test. But I can't manage to build that commit: https://gitlab.com/robertodr/pybind11-mpi4py/-/jobs/1145780818 I think I'm not getting the `mpi.cfg` correct...

**Comment by dalcinl** [comment]
Use branch [bugfix/msmpi]{https://github.com/mpi4py/mpi4py/tree/bugfix/msmpi}, I just rebased it to current master.

**Comment by robertodr** [comment]
I managed to build the branch in CI: see https://gitlab.com/robertodr/pybind11-mpi4py/-/pipelines/281951376 The test passes, but I get a warning: https://gitlab.com/robertodr/pybind11-mpi4py/-/jobs/1155766124#L207

**Comment by dalcinl** [comment]
OK, the warning is bad, things are not working as expected. This probably means that the MSMPI package from conda-forge does not define `MSMPI_VER` in its `mpi.h` header file.

**Comment by dalcinl** [comment]
I believe that the problem comes from using MSMPI from conda-forge. mpi4py is not seeing the right MS MPI version number at build time, because that does not come from `mpi.h`, but from the Windows registry (when MS MPI is installed from the official Microsoft installer packages).

@leofang @RyanMcCarthy-NOAA The MSMPI package in conda-forge is slightly broken, MSMPI_VER from `mpi.h` does not reflect the actual version number. Because of that, the mpi4py package is disabling a lot of MPI features (e.g. `MPI_Message` and matched probes).

**Comment by robertodr** [comment]
I've checked `mpi.h` in the MSMPI tarball and `MSMPI_VER` is defined. The conda-forge recipe doesn't touch the header. Also, in the `main` branch of the testing repository I do:
```c++
#ifdef MSMPI_VER
#define PyMPI_HAVE_MPI_Message 1
#endif
```
and that works without warnings or failures. Might be that my build of mpi4py in CI is not correct...

**Comment by dalcinl** [comment]
> I've checked `mpi.h` in the MSMPI tarball and `MSMPI_VER` is defined

Yes, but check the actual value of the define! mpi4py uses that value to enable MS MPI features that have been added over the years.

**Comment by dalcinl** [comment]
> Might be that my build of mpi4py in CI is not correct...

Can you somehow manage to pass `-DMSMPI_VER=0xA01` to the preprocessor or compiler flags?

**Comment by robertodr** [comment]
If you're referring to the `mpi4py` build, then can it be done through `mpi.cfg`? If you're referring to the build of my own project, then yes, I can easily add that.

**Comment by dalcinl** [comment]
> If you're referring to the `mpi4py` build, 

Yes,

> then can it be done through `mpi.cfg`?

Mmm... not sure, you are using pip, and to complicate matters, you are on Windows.

**Comment by leofang** [comment]
I think the conda-forge package is broken. A while ago I spent sometime looking into https://github.com/conda-forge/msmpi-feedstock/issues/2 (can't test MS-MPI on Azure CI), but I realized we also test mpi4py+MS-MPI on Azure in this repo and it works just fine, so something must go wrong with the `msmpi`'s Conda recipe. I've meant to switch to exe extraction from source build, but didn't have time...

**Comment by leofang** [comment]
> I believe that the problem comes from using MSMPI from conda-forge. mpi4py is not seeing the right MS MPI version number at build time, because that does not come from `mpi.h`, but from the Windows registry (when MS MPI is installed from the official Microsoft installer packages).
> 
> @leofang @RyanMcCarthy-NOAA The MSMPI package in conda-forge is slightly broken, MSMPI_VER from `mpi.h` does not reflect the actual version number. Because of that, the mpi4py package is disabling a lot of MPI features (e.g. `MPI_Message` and matched probes).

@dalcinl I am looking into this because I am rebuilding the msmpi package (conda-forge/msmpi-feedstock#6). I understand you meant to check `MSMPI_VER` via the Windows Registry:
https://github.com/mpi4py/mpi4py/blob/18f16da45eaaacfba4cc0293964e1a6548d4c6a6/conf/mpiconfig.py#L172-L187
However, I think this is fundamentally incompatible with Conda packages, as none of the Windows packages touches the registry AFAIK (I could be wrong!). 

Let me propose a two-component solution. First, let me write the correct `MSMPI_VER` to `mpi.h` (which defaults to 0x100) in the conda package. Then, in mpi4py we detect if the package is coming from Conda, and if so we avoid looking up from the registry and instead use the info from `mpi.h` directly. What do you think?

**Comment by dalcinl** [comment]
> First, let me write the correct `MSMPI_VER` to `mpi.h`

I believe this should be enough for current mpi4py release to build without any patch.

**Comment by leofang** [comment]
> > First, let me write the correct `MSMPI_VER` to `mpi.h`
> 
> I believe this should be enough for current mpi4py release to build without any patch.

Lisandro, I must have missed something. The `msmpi_ver()` function that queries the registry is not always called?

**Comment by leofang** [comment]
@robertodr btw, in case this is still a concern: I rebuilt `msmpi` on Conda-Forge so that it has the correct MPI version. Maybe you'd like to give it a shot and see if you still see any warnings/errors?

**Comment by robertodr** [comment]
> @robertodr btw, in case this is still a concern: I rebuilt `msmpi` on Conda-Forge so that it has the correct MPI version. Maybe you'd like to give it a shot and see if you still see any warnings/errors?

Uhm, now testing fails: https://gitlab.com/robertodr/pybind11-mpi4py/-/jobs/1211049781#L185

**Comment by leofang** [comment]
I guess it might be that we're still rebuilding mpi4py (https://github.com/conda-forge/mpi4py-feedstock/pull/42). Give us some time. You could also try installing `msmpi` from conda-forge but building `mpi4py` yourself.

**Comment by leofang** [comment]
Hi @robertodr Maybe you can retry your tests in ~1 hr? I just merged the mpi4py rebuild PR.

**Comment by robertodr** [comment]
The pipeline is still failing. I'm not sure whether it picked up the latest build though.

**Comment by dalcinl** [comment]
@leofang Perhaps the conda-forge msmpi package is somehow broken when used outside Azure?

**Comment by leofang** [comment]
@robertodr could you post the link to the latest failing log?

**Comment by robertodr** [comment]
here you go: https://gitlab.com/robertodr/pybind11-mpi4py/-/jobs/1217865968

**Comment by leofang** [comment]
@robertodr Do you mind to add a line `conda list` below https://gitlab.com/robertodr/pybind11-mpi4py/-/blob/main/.gitlab-ci.yml#L20 so that we can see the exact versions of the installed packages?

**Comment by leofang** [comment]
(Sorry, clicked the wrong button...)

**Comment by leofang** [comment]
Another thing to note: I always verify that the `mpi4py` conda package is working on Windows after every release. @robertodr Could you try the same workflow locally? It could be that your CI setup is not fully compatible with Conda-Forge. For example, you're using the miniforge installer from Anaconda instead of from Conda-Forge. Also, you're using vs2019, which seems too new to Conda-Forge packages (though some people started experimenting it).

**Comment by robertodr** [comment]
> @robertodr Do you mind to add a line `conda list` below https://gitlab.com/robertodr/pybind11-mpi4py/-/blob/main/.gitlab-ci.yml#L20 so that we can see the exact versions of the installed packages?

`conda list` shows that I have all the latest builds for the relevant packages.

**Comment by leofang** [comment]
Thanks, @robertodr. Looks like so indeed.

Is it possible for you to try compiling using vs2019 instead of clang?
https://gitlab.com/robertodr/pybind11-mpi4py/-/blob/main/.gitlab-ci.yml#L26

**Comment by leofang** [comment]
I think I am close to figure it out, give me some time.

**Comment by robertodr** [comment]
> Thanks, @robertodr. Looks like so indeed.
> https://gitlab.com/robertodr/pybind11-mpi4py/-/jobs/1219417858
> 
> Is it possible for you to try compiling using vs2019 instead of clang?
> https://gitlab.com/robertodr/pybind11-mpi4py/-/blob/main/.gitlab-ci.yml#L26

I could use VS, yes. However, this repo is a "proxy" for another code which needs OpenMP >= 4.5 and VS only supports up to to 2.0

**Comment by leofang** [comment]
@robertodr I have a strong confidence in the new `msmpi` build. Would you kindly restart your CI to verify please?

Long story in short: I mistakenly packaged a 32-bit `msmpi.dll`, and for a few reasons it slipped out of multiple detection mechanisms.

**Comment by leofang** [comment]
(If it still doesn't work, our last resort is to rebuild mpi4py against the latest `msmpi` (https://github.com/conda-forge/mpi4py-feedstock/pull/43), but I really don't think it's necessary.)

**Comment by robertodr** [comment]
It still fails: https://gitlab.com/robertodr/pybind11-mpi4py/-/jobs/1221796371 but at least we're back to:
```
ImportError: ValueError: mpi4py.MPI.Message size changed, may indicate binary incompatibility. Expected 40 from C header, got 32 from PyObject
```

**Comment by leofang** [comment]
Thanks for testing @robertodr! OK looks like we need a rebuild. @dalcinl Please check out https://github.com/conda-forge/mpi4py-feedstock/pull/43 when you have time.

**Comment by robertodr** [comment]
> Thanks for testing @robertodr! OK looks like we need a rebuild. @dalcinl Please check out [conda-forge/mpi4py-feedstock#43](https://github.com/conda-forge/mpi4py-feedstock/pull/43) when you have time.

Thank you for working on it so thoroughly!

**Comment by leofang** [comment]
@robertodr The rebuild's up. Would you give it a shot please?

**Comment by robertodr** [comment]
I picked up the correct conda packages, I believe: 
- msmpi: https://gitlab.com/robertodr/pybind11-mpi4py/-/jobs/1223749268#L194
- mpi4py: https://gitlab.com/robertodr/pybind11-mpi4py/-/jobs/1223749268#L193
but no luck! https://gitlab.com/robertodr/pybind11-mpi4py/-/jobs/1223749268#L243

**Comment by leofang** [comment]
@robertodr Thanks for testing. The workflow is a bit odd -- right after you activated the env, you went straight to `ctest`? Don't you need to build your project first?

**Comment by robertodr** [comment]
The build and test jobs are split in two stages. The test stage sets up the environment and picks up the build artifacts from the previous one. I can run them together, though I doubt it would make a difference.

**Comment by leofang** [comment]
Hi @robertodr I see you removed this snippet 
```C
#ifdef MSMPI_VER
#define PyMPI_HAVE_MPI_Message 1
#endif
```
But we didn't patch the mpi4py conda package, so IIUC this is still needed. Maybe you should follow Lisandro's advice on applying the patch from this branch: https://github.com/mpi4py/mpi4py/compare/bugfix/msmpi.

**Comment by leofang** [comment]
(I am obviously doing some guess work, so I could be wrong.)

**Comment by robertodr** [comment]
Running them together still gives the same result: https://gitlab.com/robertodr/pybind11-mpi4py/-/jobs/1223900024

**Comment by robertodr** [comment]
> Hi @robertodr I see you [removed this snippet](https://gitlab.com/robertodr/pybind11-mpi4py/-/compare/main...msmpi-update)
> 
> ```c
> #ifdef MSMPI_VER
> #define PyMPI_HAVE_MPI_Message 1
> #endif
> ```
> 
> But we didn't patch the mpi4py conda package, so IIUC this is still needed. Maybe you should follow Lisandro's advice on applying the patch from this branch: https://github.com/mpi4py/mpi4py/compare/bugfix/msmpi.

OK, I misunderstood the whole conversation then 🤦🏻 Indeed with the new msmpi package *and* mpi4py from the bugfix branch the build works and tests pass: https://gitlab.com/robertodr/pybind11-mpi4py/-/jobs/1223946613

**Comment by leofang** [comment]
@robertodr @dalcinl Looks like the `bugfix/msmpi` branch + the latest `msmpi` conda package makes everything work!
https://gitlab.com/robertodr/pybind11-mpi4py/-/pipelines/294561734

**Comment by leofang** [comment]
> OK, I misunderstood the whole conversation then 🤦🏻

Ha we replied at the same time. Yeah sorry I got confused too. Glad it worked out.

**Comment by robertodr** [comment]
@leofang thanks for your help!

**Comment by dalcinl** [comment]
I'll merge the `bugfix/msmpi` branch soon.

**Comment by dalcinl** [comment]
@robertodr Can you please give it a final try to the `bugfix/msmpi` branch? I just rebased that branch to latest master.
As we do not have any CI tests of our own related to wrapping on Windows, I would like your final OK before merging into master.

**Comment by robertodr** [comment]
After the rebase, it builds (https://gitlab.com/robertodr/pybind11-mpi4py/-/jobs/1226563962) and runs tests (https://gitlab.com/robertodr/pybind11-mpi4py/-/jobs/1226563986) without problems. Will there be a new release of mpi4py after the branch is merged?

**Comment by dalcinl** [comment]
@robertodr Thanks! About a new  mpi4py release, it will happen eventually, but not immediately.
However, we could easily patch the current conda-forge package to include this fix. Would that be convenient to you? 

Remember that if you pass `-DPyMPI_HAVE_MPI_Message` to your compiler flags, the current release mpi4py release still works. 

Or you can keep using the following in your code:

```
#include <mpi.h>

#ifdef MSMPI_VER
#define PyMPI_HAVE_MPI_Message 1
#endif

#include <mpi4py/mpi4py.h>
```

**Comment by dalcinl** [comment]
Fixed via bd9278e.

**Comment by robertodr** [comment]
> @robertodr Thanks! About a new mpi4py release, it will happen eventually, but not immediately.
> However, we could easily patch the current conda-forge package to include this fix. Would that be convenient to you?
> 
> Remember that if you pass `-DPyMPI_HAVE_MPI_Message` to your compiler flags, the current release mpi4py release still works.
> 
> Or you can keep using the following in your code:
> 
> ```
> #include <mpi.h>
> 
> #ifdef MSMPI_VER
> #define PyMPI_HAVE_MPI_Message 1
> #endif
> 
> #include <mpi4py/mpi4py.h>
> ```

I will keep using the `#ifdef ... #define ...` in my code, keeping an eye out for new releases. Thanks!
